title: 'The bare minimum'
subtitle: 'by Ash McKenzie'
author:
  name: Ash McKenzie
  uri: http://ashmckenzie.org
  email: ash@greenworm.com.au
theme: ashmckenzie
cache: false
content: content
disqus_short_name: ashmckenzie-org
production:
  cache: false    
  cache_dir: system/cache
  content: /home/apps/ashmckenzie/current/content
  google_analytics_code: "UA-9865706-1"