#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default, :development)

require 'active_support/dependencies'
ActiveSupport::Dependencies.autoload_paths << File.expand_path('../../lib', __FILE__)

Dir[File.join('config', 'initialisers', '*.rb')].each { |f| require "./#{f}" }

pry